{% set name = "msitools" %}
{% set version = "0.106" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/msitools/{{ version }}/msitools-{{ version }}.tar.xz
  sha256: 1ed34279cf8080f14f1b8f10e649474125492a089912e7ca70e59dfa2e5a659b

build:
  number: 1
  # Not supported on win
  skip: True   # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - meson >=1.4
    - vala
    - bison
    - flex
    - perl 5.*
    - gnuconfig
    - ninja-base
    - pkg-config
    - setuptools  # needed for vapigen/g-ir-scanner during build
  host:
    - gcab >=0.1.10
    - gettext >=0.21.0  # [osx]
    - glib >=2.12
    - libgsf >=1.14
    - libxml2 >=2.7
    - gobject-introspection  # needed for vapigen/g-ir-scanner during build
  run:
    - gettext >=0.21.0,<1.0a0  # [osx]

test:
  commands:
    - test -f $PREFIX/include/libmsi-1.0/libmsi.h
    - test -f $PREFIX/lib/libmsi-1.0${SHLIB_EXT}
    - msiextract --help
    - wixl --help

about:
  home: https://wiki.gnome.org/msitools
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: copyright
  summary: msitools is a set of programs to inspect and build Windows Installer (.MSI) files
  description: |
    msitools is a set of programs to inspect and build Windows Installer
    (.MSI) files. It is based on libmsi, a portable library to read and
    write .MSI files. libmsi in turn is a port of (and a subset of)
    Wine's implementation of the Windows Installer.
  doc_url: https://wiki.gnome.org/msitools/HowTo/CreateLibraryWxi
  dev_url: https://gitlab.gnome.org/GNOME/msitools

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
    - katietz
