{% set name = "msitools" %}
{% set version = "0.100" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnome.org/pub/GNOME/sources/msitools/{{ version }}/msitools-{{ version }}.tar.xz
  sha256: bbf1a6e3a9c2323b860a3227ac176736a3eafc4a44a67346c6844591f10978ea
  patches:  # [osx]
    - byte-order-osx.patch  # [osx]

build:
  number: 1
  # Not supported on win
  skip: True   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - bison
    - flex
    - gawk
    - gnuconfig
    - make
    - patch     # [osx]
    - perl 5.*
    - pkg-config
  host:
    - gcab
    - gettext  # [osx]
    - glib
    - libgsf 1.14.*
    - libuuid <2
    - libxml2 2.10
  run:
    - gettext  # [osx]
    - libgsf >=1.14,<1.15

test:
  commands:
    - test -f $PREFIX/include/libmsi-1.0/libmsi.h
    - test -f $PREFIX/lib/libmsi${SHLIB_EXT}
    - msiextract --help

about:
  home: https://wiki.gnome.org/msitools
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING.LIB
  summary: msitools is a set of programs to inspect and build Windows Installer (.MSI) files
  description: |
    msitools is a set of programs to inspect and build Windows Installer
    (.MSI) files. It is based on libmsi, a portable library to read and
    write .MSI files. libmsi in turn is a port of (and a subset of)
    Wine's implementation of the Windows Installer.
  doc_url: https://wiki.gnome.org/msitools/HowTo/CreateLibraryWxi
  dev_url: https://gitlab.gnome.org/GNOME/msitools

extra:
  recipe-maintainers:
    - isuruf
    - xhochy
    - katietz
