travis:
  secure:
    BINSTAR_TOKEN: NVY4OHbnk5+XFXtHvQCdwDvmOTfhw7K8La19xRfJDSlFtMOYucSARgPvGu540wOyRZNbyBiNw8TdJU0nj8CRmBwmWJoLPgGtAroXlwZizLkPlY12nEYBXOai3ZHMrUHU9/K+U/npxgaGoz2bVc3JnyCr0M6FPYTr8JOJLxi4pFu7zJwTBoGSv6OnU04Q9j0MJI/ALzHPRIZlYy9G4wPwAD3f/t0vXL7VrK6Kd2H/ldBCekqGoFq7qUcwjGYOiKFDHe/oZ0LgfWBwZN6adhaSGZUKQryj35lgxfQCsDXp3YNfs6REWu3k0xsGx3j1rEO4qlUPzEb6wPOfiURaGorMFKsCNwnckBlWauu1Y8u898VtjV/KRj+ijeNAYkdnuy8Qk1tffL4+joFM9espGIKVI+Cpn7usngJcTXIUqvSBVrgs1TZGh+NLzGs4AOaz2bvo/nyhVfychLfCXAmBnCHAuLYqMl0Od2UK+mA+KJmnPgchQ73c4I4UBvPeVAdqkEMP7TORAXM9ZRSMqNr2DjD8yPXR/tkBcjjc54D6nJjwo2udn/CNd8wTV1b0Gg3BsTtJ4JDJV12XXReyia8IoYTiIgiy5HkOmgpROyH/ENkRpi2eqV8gZQJH/ZMwlE1VyxXlhlCAfxTojPpunbwXEWKj+ze3IrcMlXFtrjmzAvFQV7I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
